[package]
authors = ["ChiHai <ihciah@gmail.com>"]
description = "Http client for Monoio."
edition = "2021"
license = "MIT/Apache-2.0"
name = "monoio-http-client"
version = "0.1.0"

[dependencies]

monoio = { version = "0.1.3" }
monoio-http = { version = "0.1.0", path = "../monoio-http" }
monoio-rustls = { version = "0.1.2", optional = true }
bytes = "1"
http = "0.2"
local-sync = "0.1"
serde = "1"
serde_json = "1"
smol_str = "0.2"
thiserror = "1"
rustls = { version = "0", default-features = false, optional = true, features = [
    "dangerous_configuration",
] }
tracing = { version = "0.1", optional = true }
webpki-roots = { version = "0.22", optional = true }
[dev-dependencies]
serde = { version = "1", features = ["derive"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }

[features]
default = ["tls", "time"]
# Enable this feature to make connection pool periodically checking works.
# You must enable time driver to use it.
time = []

logging = ["tracing", "monoio-rustls?/logging"]
tls = ["rustls", "webpki-roots", "monoio-rustls"]
unsafe-io = ["monoio-rustls?/unsafe_io"]
